function(assert_call)
    cmake_parse_arguments(assert_call "" "OUTPUT" "ARGS" ${ARGN}) 
    set(out "")
    list(LENGTH assert_call_ARGS len)
    if (len EQUAL 1)
        list(GET assert_call_ARGS 0 str)
        upper_str(${str} out)
    elseif(len EQUAL 2)
        list(GET assert_call_ARGS 0 str)
        list(GET assert_call_ARGS 1 index)
        upper_str(${str} out INDEX ${index})
    elseif(len EQUAL 3)
        list(GET assert_call_ARGS 0 str)
        list(GET assert_call_ARGS 1 index)
        list(GET assert_call_ARGS 2 length)
        upper_str(${str} out INDEX ${index} LENGTH ${length})
    endif()
    set(${assert_call_OUTPUT} ${out} PARENT_SCOPE)
endfunction(assert_call)
