function(assert_call)
    cmake_parse_arguments(assert_call "" "OUTPUT" "ARGS" ${ARGN}) 
    set(out "")
    list(GET assert_call_ARGS 0 str)
    list(GET assert_call_ARGS 1 length)
    upper_str(${str} out LENGTH ${length})
    set(${assert_call_OUTPUT} ${out} PARENT_SCOPE)
endfunction(assert_call)
