function(get_test_target_name_set_tag tag output)
    cmake_parse_arguments(get_test_target_name_set_tag "" "" "ARGS" ${ARGN}) 
    list(GET get_test_target_name_set_tag_ARGS 0 index)
    set("${output}" "${tag}-${index}" PARENT_SCOPE)
endfunction(get_test_target_name_set_tag )
