function(assert_call)
    cmake_parse_arguments(assert_call "" "OUTPUT" "ARGS" ${ARGN}) 
    list(GET assert_call_ARGS 0 str)
    list(REMOVE_AT assert_call_ARGS 0)
    set(count 0)
    foreach(it ${assert_call_ARGS})
        if("${it}" STREQUAL "${str}")
            math(EXPR count "${count}+1")
        endif()
    endforeach(it)
    set(${assert_call_OUTPUT} ${count} PARENT_SCOPE)
endfunction(assert_call)
